blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
]

maktab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('account/', include('account.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('index.urls', namespace='index')),


]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

app_name = 'blog'

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    CATEGORY_CHOICES = (
        ('maktabga', 'Maktabga oid'),
        ('talimga', 'Ta\'limga oid'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    image = models.ImageField(upload_to='blog/%Y/%m/%d', blank=True, default='blog/no_image.png')
    category = models.CharField(max_length=100,choices=CATEGORY_CHOICES,default='maktabga')
    views = models.IntegerField(default=0, verbose_name='Views')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month,
        											self.publish.day, self.slug])

index/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

app_name = 'index'

class Science(models.Model):
	SCIENCE_STATUS = (('active', 'Active'), ('inactive', 'InActive'),)
	name = models.CharField(max_length=250,)
	status = models.CharField(max_length=10, choices=SCIENCE_STATUS, default='inactive')
	def __str__(self):
		return self.name
		
class Teachers(models.Model):
    STATUS_CHOICES = (('active', 'Active'), ('inactive', 'InActive'),)
    DEGREE_CHOICES = (
        ('mutaxasis', 'Mutaxasis'), ('ikkinchi', 'Ikkinchi toifa'),
        ('birinchi', 'Birinchi toifa'), ('oliy', 'Oliy toifa'),
    )
    GRADE_CHOICES = (
        ('direktor', 'Direktor'), ('mmibdu', 'MMIBDO\''),
        ('uibdu', 'O\'IBDO\''), ('uqtuvchi', 'O\'qtuvchi'),('psixolog', 'Psixolog'),
    )
    full_name = models.CharField(max_length=250,)
    birth_date = models.DateField()
    science = models.ManyToManyField(Science,)
    degree = models.CharField(max_length=20, choices=DEGREE_CHOICES,default='mutaxasis')
    grade = models.CharField(max_length=20, choices=GRADE_CHOICES,default='uqtuvchi')
    image = models.ImageField(upload_to='teachers/', blank=True, default='teachers/no_image.png')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='inactive')

    class Meta:
        ordering = ('full_name',)
    
    def __str__(self):
        return self.full_name

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from taggit.models import Tag
from .models import Post

def post_list(request, tag_slug=None):

    object_list = Post.objects.filter(status='published').all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,'blog/post/blog.html', locals())


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug = post, status = 'published', publish__year = year,
    							publish__month = month, publish__day = day)
    post.views += 1
    post.save()

    last_posts = Post.objects.order_by("-publish")[:3]
    all_tags = Tag.objects.all()
   
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:3]

    return render(request, 'blog/post/blog-details.html', locals() )

index/views.py
from django.shortcuts import render
from blog.models import Post
from .models import Teachers

# Create your views here.

def index(request):
    posts = Post.objects.filter(status = 'published', category='maktabga')[:3]
    teachers=Teachers.objects.filter(status='active')[:4]
    teacherss=Teachers.objects.filter(status='active'). all()
    jami=oliy=bir=ikki=mut=0
    for teach in teacherss:
        if teach.degree =='oliy':
            oliy+=1
        if teach.degree =='birinchi':
            bir+=1
        if teach.degree =='ikkinchi':
            ikki+=1
        if teach.degree =='mutaxasis':
            mut+=1
        jami+=1
    #tposts = Post.objects.filter(status = 'published', category='ta\'limga')[:4]
    return render(request, 'index.html', locals())

templates/blog/post/blog-details.html
{% extends "../../base.html" %}
{% load static %}

        {% block title %} Batafsil | 45-maktab {% endblock %}

        {% block content %}
                <!--Breadcrumb Banner Area Start-->
                <div class="breadcrumb-banner-area">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="breadcrumb-text">
                                    <h1 class="text-center">Batafsil</h1>
                                    <div class="breadcrumb-bar">
                                        <ul class="breadcrumb text-center">
                                            <li><a href="{% url 'index:index' %}">Bosh sahifa</a></li>
                                            <li><a href="{% url 'blog:post_list' %}">Yangiliklar</a></li>
                                            <li>Batafsil</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End of Breadcrumb Banner Area-->
                <!--News Details Area Start-->
                <div class="news-details-area section-padding">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-9 col-md-12 col-12">
                                <div class="news-details-content">
                                   <div class="single-latest-item">
                                        <img src="{{ post.image.url }}" alt="">  
                                        <div class="single-latest-text">
                                            <h3>{{ post.title }}</h3> 
                                            <div class="single-item-comment-view">
                                               <span><i class="zmdi zmdi-calendar-check"></i>{{post.publish|date:'d.m.y'}}</span>
                                               <span><i class="zmdi zmdi-eye"></i>{{ post.views }}</span>
                                               <span><i class="zmdi zmdi-comments"></i>19</span>
                                            </div>
                                            <p>{{ post.body }}</p>
                                            <div class="tags-and-links">
                                                <div class="related-tag">
                                                    <span>Tag:</span>
                                                    <ul class="tags">
        {% for tag in post.tags.all %}
            <li>
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            </li>                     
        {% endfor %}            
                                                    </ul>
                                            </div>
                                        <div class="social-links">
                                            <span>Share:</span>
                                            <a href="#"><i class="zmdi zmdi-facebook"></i></a>
                                            <a href="#"><i class="zmdi zmdi-twitter"></i></a>
                                            <a href="#"><i class="zmdi zmdi-google-old"></i></a>
                                            <a href="#"><i class="zmdi zmdi-instagram"></i></a>
                                        </div>
                                    </div>
                                        </div>
                                    </div>
                                </div>    
                            </div>
                            <div class="col-lg-3 col-md-12 col-12">
                                <div class="sidebar-widget">
                                    {% if similar_posts %}
                                    <div class="single-sidebar-widget">
                                        <h4 class="title">Similar Posts</h4>
                                        <div class="recent-content">
                                            {% for tag in similar_posts %}
                                                <div class="recent-content-item">
                                                    <a href="{{tag.get_absolute_url}}">
                                                        <img src="{{tag.image.url}}" alt="{{tag.title}}" width="70" height="67">
                                                    </a>
                                                    <div class="recent-text">
                                                        <h4>
                                                            <a href="{{ tag.get_absolute_url }}">
                                                                {{ tag.title }}
                                                            </a>
                                                        </h4>
                                                        <div class="single-item-comment-view">
                                                            <span><i class="zmdi zmdi-eye"></i>{{ tag.views }}</span>
                                                            <span><i class="zmdi zmdi-comments"></i>19</span>
                                                        </div>
                                                        <p>{{ tag.body|slice:'50' }}</p>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                                    <div class="single-sidebar-widget">
                                        <h4 class="title">Recent Posts</h4>
                                        <div class="recent-content">
                                            {% for last_post in last_posts  %}
                                            
                                            <div class="recent-content-item">
                                                <a href="{{last_post.get_absolute_url}}"><img src="{{last_post.image.url}}" alt="{{last_post.title}}" width="70" height="67"></a>
                                                <div class="recent-text">
                                                    <h4><a href="{{last_post.get_absolute_url}}">{{last_post.title}}</a></h4>
                                                    <div class="single-item-comment-view">
                                                        <span><i class="zmdi zmdi-eye"></i>{{last_post.views}}</span>
                                                        <span><i class="zmdi zmdi-comments"></i>19</span>
                                                    </div>
                                                    <p>{{last_post.body|slice:'50'}}</p>
                                                </div>
                                            </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="single-sidebar-widget">
                                        <h4 class="title">Search by Tags</h4>
                                        <ul class="tags">
                                            {% for tags in all_tags  %}
                                                <li>
                                                    <a href="{% url 'blog:post_list_by_tag' tags.slug %}">{{tags.name}}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                    </div>
                        </div>
                    </div>
                </div>
                <!--End of News Details Area-->
        {% endblock %}

templates/blog/post/blog.html
{% extends "../../base.html" %}
{% load static %}

            {% block title %} Yangiliklar | 45-maktab {% endblock %}

            {% block content %}
                <!--Breadcrumb Banner Area Start-->
                <div class="breadcrumb-banner-area">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="breadcrumb-text">
                                    <h1 class="text-center">Maktab hayotiga oid yangiliklar</h1>
                                    <div class="breadcrumb-bar">
                                        <ul class="breadcrumb text-center">
                                            <li><a href="{ url 'index:index' }">Bosh sahifa</a></li>
                                            <li>Yangiliklar</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End of Breadcrumb Banner Area-->

                <!--Course Area Start-->
                <div class="course-area section-padding course-page">
                    <div class="container">
                        {% for post in posts %}
                        <div class="row">
                            <div class="col-lg-4 col-md-6 col-12">
                                <div class="single-item">
                                    <div class="single-item-image overlay-effect">
                                        <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" alt=""></a>
                                    </div>
                                    <div class="single-item-text">
                                        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                                        <div class="single-item-text-info">
                                            <span>By: <span>{{ post.auther }}</span></span>
                                            <span>Date: <span>{{ post.publish|date:"d.m.y" }}</span></span>
                                        </div>
                                        <p>{{ post.body }} </p>
                                        <div class="single-item-content">
                                           <div class="single-item-comment-view">
                                               <span><i class="zmdi zmdi-eye"></i>{{post.views}}</span>
                                               <span><i class="zmdi zmdi-comments"></i>19</span>
                                           </div>
                                           <div class="single-item-rating">
                                               <i class="zmdi zmdi-star"></i>
                                               <i class="zmdi zmdi-star"></i>
                                               <i class="zmdi zmdi-star"></i>
                                               <i class="zmdi zmdi-star"></i>
                                               <i class="zmdi zmdi-star-half"></i>
                                           </div>
                                        </div>   
                                    </div>
                                    <div class="button-bottom">
                                        <a href="{{ post.get_absolute_url }}" class="button-default">Batafsil</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="pagination-content">
                                    <ul class="pagination">
                                        <li><a href="#"><i class="zmdi zmdi-chevron-left"></i></a></li>
                                        <li class="current"><a href="#"><i class="zmdi zmdi-chevron-right"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End of Course Area-->
                {% endblock %}
                